### ISSUE TITLE
The `--kvnr` filter removes all results from `erpione fetch accepted`  

### ISSUE THREAD

**Issue by alisianoi** [gematik/erp-e2e-testsuite#2] opened 2024-02-06 14:02 UTC
Steps to reproduce:

```
# Pull the image, start a container with a valid API KEY:
$ docker pull gematik1/erpione:0.2.1
$ docker run -it --entrypoint /bin/zsh --env ERPIONE_API_KEY=${ERPIONE_API_KEY} gematik1/erpione:0.2.1

# Fetch all accepted prescriptions (result attached as erpione-fetch-accepted.log)
$ erpione fetch accepted --env ru

# Select one KVNR from the above output, and use it in the filter
$ erpione fetch accepted --env ru --kvnr K220635158
Found 0 accepted prescriptions with filter KVNR=K220635158
----------
[]
```

I would expect the last command to return prescriptions related to the selected KVNR. However, instead it returns 0 prescriptions. Is this a bug or do I misunderstand that filter?

Same question for the `open` and `dispensed` use cases.

[erpione-fetch-accepted.log](https://github.com/gematik/erp-e2e-testsuite/files/14181203/erpione-fetch-accepted.log)

**Comment by alexanderkaiser** [comment] 2024-02-07 08:23
Hello @alisianoi thank for raising the issue. I can confirm and reproduce the bug.

I will prepare a fix for this issue which will be available in gematik1/erpione:0.2.2

**Comment by alexanderkaiser** [comment] 2024-02-07 08:39
The bug was introduced with the refactoring of response-structures of the PrimSys-Backend in [v0.5.0](https://github.com/gematik/erp-e2e-testsuite/blob/master/ReleaseNotes.md#release-050). The same issue applies also to `dispensed`. 
However, on `open` I was not able to reproduce the issue: @alisianoi can you confirm that or provide an example?

**Comment by alisianoi** [comment] 2024-02-08 08:04
@alexanderkaiser you're right, the issue does _not_ exist for `open`, my mistake.

For the other two (`accepted` and `dispensed`), it does exist

**Comment by alexanderkaiser** [comment] 2024-02-08 08:54
@alisianoi I have released erpione:0.2.2 with the fix. Would be great if you could double-check the fix

**Comment by alisianoi** [comment] 2024-02-08 09:03
@alexanderkaiser thank you for the quick fix! Works for me

**Comment by alexanderkaiser** [comment] 2024-02-08 09:43
👍

**Closed as completed by alexanderkaiser** 2024-02-08 09:43 UTC
